service: github-stats

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  environment:
    GITHUB_USERNAME: ${env:GITHUB_USERNAME, ''}
    GITHUB_TOKEN: ${env:GITHUB_TOKEN, ''}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME, ''}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${env:S3_BUCKET_NAME, 'github-repository-stats'}/*"

plugins:
  - serverless-python-requirements # Bundle dependencies for Lambda
  - serverless-dotenv-plugin # Inject environment variables from .env

custom:
  pythonRequirements:
    pythonBin: python3

package:
  patterns:
    - "!**"
    - handler.py
    - generate.py
    - upload.py

functions:
  main:
    handler: handler.main
    description: Simple connectivity test
    memorySize: 128
    timeout: 30
    events:
      - schedule:
          rate: cron(0 19 * * ? *) # 毎日UTC 19:00 = 日本時間 4:00
          enabled: true
